# Generated by Django 6.0.2 on 2026-02-19 14:47

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=core.models._generate_code, editable=False, help_text='Code temporaire à 6 chiffres (généré automatiquement).', max_length=6)),
                ('starts_at', models.DateTimeField(help_text="Début de l'expérience.")),
                ('expires_at', models.DateTimeField(help_text="Fin de l'expérience.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_experiencesession',
                'ordering': ['-created_at'],
            },
        ),
    ]
